name: parkhive_app
description: Starter Flutter app for ParkHive (Login/Register)
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI & Dialog
  awesome_dialog: ^3.2.1

  # Fonts & Icons
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  font_awesome_flutter: ^10.7.0

  # Networking & Local Storage
  http: ^1.2.0
  shared_preferences: ^2.2.2

  # Location & Permission
  geolocator: ^13.0.1
  geocoding: ^3.0.0
  permission_handler: ^11.3.1

  # Media
  image_picker: ^1.1.2

  # Map
  flutter_map: ^8.2.2
  latlong2: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/profil.jpeg
